#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"
umask 077
mkdir -p "_local-test"
chmod 700 "_local-test"
ENV_FILE="_local-test/phone.env"
touch "$ENV_FILE"
chmod 600 "$ENV_FILE"
CA_DIR="${HOME}/Library/Mobile Documents/com~apple~CloudDocs/custom_ca"

banner "Local test: phone setup"

stage "Sign a LAN certificate manually"
say "This stage never runs the signing script. The CA directory is: $CA_DIR"
say "The next command prints the current LAN address and canonical HTTPS URL."
if ! pnpm local:info; then
  warn "local:info failed; finish local test database setup before continuing."
  exit 1
fi
step "In a separate terminal, open the CA directory and run: bash ./generate_cert.sh >/dev/null"
say "Enter the current LAN IP, answer n for extra names/IPs, and accept the default validity (n)."
warn "Do not paste or display private-key contents. Use private.key as the app key, never CAPrivate.key."
ask LOCAL_TEST_LAN_IP "LAN IPv4 shown by local:info:"
if [[ -z "$LOCAL_TEST_LAN_IP" ]]; then
  warn "A LAN IPv4 address is required. Re-run this wizard after local:info can show one."
  exit 1
fi
ask LOCAL_TEST_CERT_FILE "Signed leaf certificate path:"
[[ -n "$LOCAL_TEST_CERT_FILE" ]] || LOCAL_TEST_CERT_FILE="$CA_DIR/$LOCAL_TEST_LAN_IP/$LOCAL_TEST_LAN_IP.crt"
ask LOCAL_TEST_KEY_FILE "Leaf private-key file path (path only):"
[[ -n "$LOCAL_TEST_KEY_FILE" ]] || LOCAL_TEST_KEY_FILE="$CA_DIR/private.key"
ask LOCAL_TEST_CA_FILE "Public CA certificate path:"
[[ -n "$LOCAL_TEST_CA_FILE" ]] || LOCAL_TEST_CA_FILE="$CA_DIR/CAPrivate.pem"
step "Save the selected certificate paths and update local test configuration (no key contents are read)."
write_env LOCAL_TEST_LAN_IP "$LOCAL_TEST_LAN_IP"
write_env LOCAL_TEST_CERT_FILE "$LOCAL_TEST_CERT_FILE"
write_env LOCAL_TEST_KEY_FILE "$LOCAL_TEST_KEY_FILE"
write_env LOCAL_TEST_CA_FILE "$LOCAL_TEST_CA_FILE"
chmod 600 "$ENV_FILE"
pnpm local:init -- --lan-ip "$LOCAL_TEST_LAN_IP" --cert-file "$LOCAL_TEST_CERT_FILE" --key-file "$LOCAL_TEST_KEY_FILE" --ca-file "$LOCAL_TEST_CA_FILE"

stage "Check public CA trust on devices"
open_url "https://support.apple.com/en-us/102390"
say "Only share/install the public CA certificate CAPrivate.pem. Never share CAPrivate.key or private.key."
step "On each device, check whether this CA is already trusted. Install the public CA only if it is not. Do not remove existing certificates."
say "iPhone/iPad: install the public CA profile, then Settings → General → About → Certificate Trust Settings → enable full trust for this CA."
say "Android: use the device's CA certificate settings and verify it is trusted by the browser; do not use a Wi-Fi certificate-only menu. Menu names vary by device."
say "On this Mac, verify there is no browser certificate warning; prior command-line CA verification does not replace the browser check."
if ! confirm "Have you checked trust on the devices, and installed only the public CA where needed?"; then
  warn "Trust is not confirmed. Stop here and re-run the wizard when device trust is ready."
  write_env LOCAL_TEST_CA_TRUST "not_confirmed"
  chmod 600 "$ENV_FILE"
  exit 1
fi
write_env LOCAL_TEST_CA_TRUST "confirmed"
chmod 600 "$ENV_FILE"

stage "Open the HTTPS app from phone and Mac"
say "In another terminal, start pnpm local:dev and leave it running. This wizard does not start or stop application services."
say "Use the exact canonical HTTPS URL shown by local:info on both Mac and phone."
say "Check the home page, administrator login, and scan-entry page. Confirm there is no TLS warning and the browser reports a secure context."
warn "If the page is unreachable, check LAN/client isolation, VPN routing, or the firewall manually. Do not disable the firewall/VPN automatically or create a tunnel."
if ! confirm "Can the phone open the HTTPS app with no certificate warning?"; then
  write_env LOCAL_TEST_PHONE_CONNECTIVITY "not_confirmed"
  chmod 600 "$ENV_FILE"
  warn "Phone connectivity is not confirmed; resolve the LAN/TLS issue and re-run this wizard."
  exit 1
fi
write_env LOCAL_TEST_PHONE_CONNECTIVITY "confirmed"
chmod 600 "$ENV_FILE"

stage "Test phone location and real business flows"
say "In the administrator interface, change only the dedicated '手机定位测试地点' location to the phone's current location."
say "Keep real coordinates only in the isolated local-test database; never enter them in this script or phone.env."
step "Use the location event to check denied permission, granted permission, and in/out-of-range validation."
step "Scan to exercise preregistered or onsite ticketing, then test consecutive-event seat selection and results."
say "This stage is a human acceptance check; an unconfirmed result is not a pass."
if confirm "Did you complete and confirm the phone location and business-flow checks?"; then
  write_env LOCAL_TEST_PHONE_VERIFICATION "completed"
  chmod 600 "$ENV_FILE"
  finish
else
  write_env LOCAL_TEST_PHONE_VERIFICATION "not_completed"
  chmod 600 "$ENV_FILE"
  warn "Phone verification remains not completed. Run this wizard again after finishing the checks."
fi

say "Canonical address and current paths:"
pnpm local:info
say "Show only the local administrator password: pnpm local:credentials"
say "Start: pnpm local:dev"
say "Stop the foreground app with Ctrl-C, then stop only the test DB: pnpm local:stop"
say "Restore synthetic data only when manual changes may be discarded: pnpm local:reset"
say "Reset preserves credentials and certificates; type pickseat_local_test to confirm."
