"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";

export type SeatDto = { id: string; rowIndex: number; columnIndex: number; rowLabel: string; columnLabel: string; kind: "seat" | "aisle" | "empty"; selectable: boolean; golden: boolean };
export function SeatPicker({ code, eventName, seats, initialOccupied, initialVersion, ticketTotal, centerAfterColumn }: { code: string; eventName: string; seats: SeatDto[]; initialOccupied: string[]; initialVersion: number; ticketTotal: number; centerAfterColumn: number | null }) {
  const router = useRouter(); const [selected, setSelected] = useState<string[]>([]); const [occupied, setOccupied] = useState(() => new Set(initialOccupied)); const [version, setVersion] = useState(initialVersion); const [toast, setToast] = useState(""); const [busy, setBusy] = useState(false);
  const columns = Math.max(...seats.map((seat) => seat.columnIndex), 0) + 1;
  const showToast = useCallback((message: string) => { setToast(message); setTimeout(() => setToast(""), 2600); }, []);
  const refresh = useCallback(async () => { const response = await fetch(`/api/events/${code}/seat-state?version=${version}`, { cache: "no-store" }); if (response.status === 204) return; if (!response.ok) return; const data = await response.json() as { version: number; occupiedSeatIds: string[] }; const next = new Set(data.occupiedSeatIds); setVersion(data.version); setOccupied(next); setSelected((old) => { const available = old.filter((id) => !next.has(id)); if (available.length !== old.length) showToast("你选中的座位刚刚被他人确认，请重新选择。"); return available; }); }, [code, showToast, version]);
  useEffect(() => { const interval = setInterval(() => void refresh(), document.hidden ? 15_000 : 3_000); const onVisibility = () => { if (!document.hidden) void refresh(); }; document.addEventListener("visibilitychange", onVisibility); window.addEventListener("online", onVisibility); return () => { clearInterval(interval); document.removeEventListener("visibilitychange", onVisibility); window.removeEventListener("online", onVisibility); }; }, [refresh]);
  function toggle(seat: SeatDto) { if (occupied.has(seat.id)) { showToast("这个座位已被其他参与者选择。"); return; } if (!seat.selectable || seat.kind !== "seat") return; setSelected((old) => old.includes(seat.id) ? old.filter((id) => id !== seat.id) : old.length >= ticketTotal ? (showToast(`最多选择 ${ticketTotal} 个座位`), old) : [...old, seat.id]); }
  function confirm() { if (selected.length !== ticketTotal) return; setBusy(true); navigator.geolocation.getCurrentPosition(async (position) => { const location = await fetch("/api/location/verify", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ latitude: position.coords.latitude, longitude: position.coords.longitude, accuracy: position.coords.accuracy, capturedAt: position.timestamp }) }); if (!location.ok) { setBusy(false); showToast("确认前的定位验证未通过。"); return; } const response = await fetch(`/api/events/${code}/confirm`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ seatIds: selected }) }); setBusy(false); if (response.ok) router.refresh(); else { showToast(response.status === 409 ? "部分座位已被抢先确认，请重新选择。" : "确认失败，请稍后重试。"); await refresh(); } }, () => { setBusy(false); showToast("无法获取定位，暂时不能确认选座。"); }, { enableHighAccuracy: true, timeout: 12_000, maximumAge: 0 }); }
  const selectedLabels = useMemo(() => selected.map((id) => { const seat = seats.find((item) => item.id === id); return seat ? `${seat.rowLabel}${seat.columnLabel}` : ""; }).filter(Boolean), [seats, selected]);
  return <main className="seat-page"><header><p className="eyebrow">{eventName}</p><h1>挑选你的座位</h1><div className="legend"><span className="available">可选</span><span className="golden">黄金区</span><span className="occupied">已选</span><span className="blocked">不可选</span></div></header><section className="seat-map-wrap"><div className="screen">银幕方向</div><div className="public-seat-grid" style={{ gridTemplateColumns: `repeat(${columns}, 42px)` }}>{seats.map((seat) => <button key={seat.id} type="button" aria-label={`${seat.rowLabel}${seat.columnLabel}`} disabled={seat.kind !== "seat" || !seat.selectable} className={`public-seat ${seat.kind} ${seat.golden ? "golden" : ""} ${occupied.has(seat.id) ? "occupied" : ""} ${selected.includes(seat.id) ? "mine" : ""} ${centerAfterColumn === seat.columnIndex ? "center-gap" : ""}`} onClick={() => toggle(seat)}>{seat.kind === "seat" ? seat.columnIndex + 1 : ""}</button>)}</div></section><footer className="selection-bar"><div><strong>已选 {selected.length}/{ticketTotal}</strong><span>{selectedLabels.length ? selectedLabels.join("、") : "请在上方点选座位"}</span></div><button className="button primary" disabled={selected.length !== ticketTotal || busy} onClick={confirm}>{busy ? "正在确认…" : "确认选座"}</button></footer>{toast ? <div className="toast" role="status">{toast}</div> : null}</main>;
}
